openapi: 3.0.0
servers:
  - url: http://petstore.swagger.io/v1
info:
  version: ""
  title: ""
paths:
  /pet/{name}:
    put:
      operationId: updatePet
      x-scala-package: pet
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: ""
          content:
            "multipart/form-data":
              schema:
                $ref: "#/components/schemas/Pet"
  /pets:
    get:
      operationId: getPets
      x-scala-package: pet
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: array
                  items:
                    type: string
                status:
                  type: string
              required:
                - name
      responses:
        "200":
          description: ""
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
    post:
      operationId: createPet
      x-scala-package: pet
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                status:
                  type: string
              required:
                - name
#          multipart/form-data:
#            schema:
#              properties:
#                name:
#                  type: string
#                status:
#                  type: string
#                file:
#                  type: string
#                  format: binary
#              required:
#                - name
#          application/json:
#            schema:
#              $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: ""
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      type: object
      required:
      - name
      properties:
        name:
          type: string
        status:
          type: string
